lib: [
  "_build/install/default/lib/ocamlgpt/META"
  "_build/install/default/lib/ocamlgpt/dune-package"
  "_build/install/default/lib/ocamlgpt/lib/microgpt.a" {"lib/microgpt.a"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cma" {"lib/microgpt.cma"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cmi" {"lib/microgpt.cmi"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cmt" {"lib/microgpt.cmt"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cmx" {"lib/microgpt.cmx"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cmxa" {"lib/microgpt.cmxa"}
  "_build/install/default/lib/ocamlgpt/lib/microgpt.ml" {"lib/microgpt.ml"}
  "_build/install/default/lib/ocamlgpt/opam"
]
libexec: [
  "_build/install/default/lib/ocamlgpt/lib/microgpt.cmxs" {"lib/microgpt.cmxs"}
]
bin: [
  "_build/install/default/bin/ocamlgpt"
]
doc: [
  "_build/install/default/doc/ocamlgpt/README.md"
]
